# Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
# Kotlin
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
# Incremental compilation
kotlin.incremental=true
kotlin.incremental.multiplatform=true
